xephem_edb_objecttypes = {
        "A": "Cluster of galaxies",
        "B": "Star, binary",
        "C": "Cluster, globular",
        "D": "Star, visual double",
        "F": "Nebula, diffuse",
        "G": "Galaxy, spiral",
        "H": "Galaxy, spherical",
        "J": "Radio",
        "K": "Nebula, dark",
        "L": "Pulsar",
        "M": "Star, multiple",
        "N": "Nebula, bright",
        "O": "Cluster, open",
        "P": "Nebula, planetary",
        "Q": "Quasar",
        "R": "Supernova remnant",
        "S": "Star",
        "T": "Stellar object",
        "U": "Cluster, with nebulosity",
        "Y": "Supernova",
        "V": "Star, variable",
    }
